// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTWpDCyblw0ymCkhQZ2zreHag3843A5Q',
    appId: '1:149221473756:web:16bf7b203c3804e636a319',
    messagingSenderId: '149221473756',
    projectId: 'educycle-2f92b',
    authDomain: 'educycle-2f92b.firebaseapp.com',
    storageBucket: 'educycle-2f92b.firebasestorage.app',
    measurementId: 'G-BCB7L91SDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IuV4k5e96PaOLI8un2Y3yxBAXBeQiVM',
    appId: '1:149221473756:android:e8dd34d4df8ffef036a319',
    messagingSenderId: '149221473756',
    projectId: 'educycle-2f92b',
    storageBucket: 'educycle-2f92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwT1kx5i1JfD9OGFIJ3jbQrKZM8KUEALc',
    appId: '1:149221473756:ios:19c730657219e16936a319',
    messagingSenderId: '149221473756',
    projectId: 'educycle-2f92b',
    storageBucket: 'educycle-2f92b.firebasestorage.app',
    iosBundleId: 'com.example.educycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwT1kx5i1JfD9OGFIJ3jbQrKZM8KUEALc',
    appId: '1:149221473756:ios:19c730657219e16936a319',
    messagingSenderId: '149221473756',
    projectId: 'educycle-2f92b',
    storageBucket: 'educycle-2f92b.firebasestorage.app',
    iosBundleId: 'com.example.educycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDTWpDCyblw0ymCkhQZ2zreHag3843A5Q',
    appId: '1:149221473756:web:f2de1bc0036e432036a319',
    messagingSenderId: '149221473756',
    projectId: 'educycle-2f92b',
    authDomain: 'educycle-2f92b.firebaseapp.com',
    storageBucket: 'educycle-2f92b.firebasestorage.app',
    measurementId: 'G-WP7165PJ2Q',
  );
}
